security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # users_in_memory: { memory: null }
        user: #Definir le provider
            entity: {class : App\Entity\User, property : email} #Defini l'entity, puis la propriete utilisee pour la connexion
    encoders:
            App\Entity\User:
                algorithm: auto
                cost: 15  
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api/
            stateless: true
            anonymous: true
            provider: user
            guard:
                authenticators:
                    ["lexik_jwt_authentication.jwt_token_authenticator"]
        
        main:
            anonymous: true
            json_login:
                check_path: /login
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            # lazy: true
            # provider: users_in_memory
            #Les trois proprietes precedentes ont ete mis en commentaire pour configurer le firewall 
            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/users/[0-9]+/eneable, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        #Préciser le "is_authenticated_full" pour les opérations de types POST, PUT et DELETE sur la ressource "Post"
         #- { path: ^/admin, roles: ROLE_ADMIN }
         #- { path: ^/profile, roles: ROLE_USER }
